# TOML Documentation: https://github.com/toml-lang/toml
# How to use bonnie: https://dev.to/arctic_hen7/an-alternative-to-npm-and-yarn-scripts-bonnie-2idd

# run these scripts with bonnie in your path, 
# for example: bonnie start

# NOTE: These scripts use the new `docker compose` (without a dash) command
# See: https://docs.docker.com/compose/cli-command/ 
# And: https://docs.docker.com/compose/cli-command-compatibility/

# Mandatory from 0.2.0 onwards
version = "0.3.1"

[scripts]
    start       = "doppler run -- docker-compose up --remove-orphans -d"
    stop        = "doppler run -- docker-compose down"
    restart     = "doppler run -- docker-compose restart"
    logs        = "doppler run -- docker-compose logs -f minio"
    pull-git    = "git pull --ff"
    pull-docker = "doppler run -- docker-compose pull"
    update      = "bonnie stop && bonnie pull-git && bonnie pull-docker && bonnie start"
