version: '3.7'

networks:
  web:
    external:
      name: traefikv2

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: ${SERVICE_DOMAIN}
    # see official docker-compose for clues
    # https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
    # command: 'server --console-address :9001 /data' # http://minio{1...4}/data{1...2}
    command: 'server /data' # http://minio{1...4}/data{1...2}
    # restart: always
    volumes:
      - ${MINIO_DATA_ROOT}/main:/data
    environment:
      # from doppler-cli service
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: 'https://${SERVICE_DOMAIN}'
      # MINIO_BROWSER_REDIRECT_URL: 'https://dashboard.${SERVICE_DOMAIN}'
      MINIO_REGION_NAME: 'germany'
      MINIO_REGION_COMMENT: 'Custom Region for jb services'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - web
    expose:
      - '9000'
      - '9001'
    labels:
      # Traefik V2 Config
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefikv2'
      - 'traefik.http.routers.minio.rule=Host(`${SERVICE_DOMAIN}`)'
      - 'traefik.http.routers.minio.service=minio@docker'
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'
      - 'traefik.http.routers.minio.tls=true'
      - 'traefik.http.routers.minio.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.minio.tls.domains[0].main=${SERVICE_DOMAIN}'

      # Labels for MinIO Dashboard connection
      # Adapted from here: https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples
      - traefik.http.routers.minio-dashboard.rule=Host(`dashboard.${SERVICE_DOMAIN}`)
      - traefik.http.routers.minio-dashboard.service=minio-dashboard
      - traefik.http.services.minio-dashboard.loadbalancer.server.port=9001
